version: '3'
services:
  db:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbPoKey
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: app
    stdin_open: true
    tty: true # для открытия терминала после старта
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: dbPoKey